---
handlers:

    - name: restart ssh
      service:
        name: memcached
        state: restarted

    - name: reload nginx config
      command: nginx -s reload

    - name: restart nginx
      service:
        name: nginx
        state: restarted