#!/usr/bin/env bash

alias l='ls -lach'
alias ll='ls -lch'

alias ..='..'
alias ...='../..'
alias ....='../../..'
alias .....='../../../..'

alias tree='tree -C --dirsfirst'

alias po=popd
alias pu=pushd

alias ga='git add'
alias gaa='git add --all'

alias gst='git status'
alias gb='git branch'
alias gba='git branch -a'

alias gc='git commit -v'
alias 'gc!'='git commit -v --amend'
alias 'gca!'='git commit -v -a --amend'

alias glg='git log --stat'
alias glgg='git log --graph'
alias glog='git log --oneline --decorate --graph'
alias glol='git log --graph --pretty=format:'\''%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset'\'' --abbrev-commit'

alias gl='git pull'
alias gp='git push'
alias gco='git checkout'

alias grh='git reset HEAD'
alias grhh='git reset HEAD --hard'
